### ISSUE TITLE
Naming conventions on guidelines

### ISSUE THREAD

**Issue by bra001** [equinor/appsec#139]
Over time more and more guidelines have been written.
It now is clear that there is no "naming convention" on the titles of the guidelines:
![image](https://github.com/equinor/appsec/assets/9586805/31444276-e521-4e38-b9b6-e00860571383)

Make a convention such that:
* The title only states what the guideline is about (avoid having the word "guideline" in the title itself)

**Comment by aigelonic** [comment]
Closing issue - was resolved by #140
