### ISSUE TITLE
Add a relevant security guideline - containers

### ISSUE THREAD

**Issue by larskaare** [equinor/appsec#47]
Add a AppSec related security guideline to the docs/resources/guidelines area.

**Comment by The-Debarghya** [comment]
Hey, can I add container security guidelines in the guidelines_containers.md file?
If yes please can you assign it to me

**Comment by larskaare** [comment]
Thanx @The-Debarghya - looking forward to your contriution for containers in the context of application security

**Comment by kaptan0428** [comment]
I would like to contribute, Can you assign this task to me ?

**Comment by ReedOnly** [comment]
PR merged and content published: https://equinor.github.io/appsec/resources/guidelines/guideline_containers/
Thanks for contribution @The-Debarghya 🥳
