### ISSUE TITLE
Enhance guideline - secure coding

### ISSUE THREAD

**Issue by ipsitamishra16893** [equinor/appsec#49]
Enhance the [guideline on secure coding](https://github.com/equinor/appsec/blob/6b3c265088c73a57fc246979fa11568eb71b00dc/docs/resources/guidelines/guideline_secure_coding.md) by adding a section about securely processing files.

**Comment by kaptan0428** [comment]
I would like to contribute, Can you assign this task to me ?

**Comment by ipsitamishra16893** [comment]
Thanks @kaptan0428 - looking forward to your contribution

**Comment by larskaare** [comment]
Dormant, closing.
