### ISSUE TITLE
resources/security_requirements: Add some examples of Security Requirements

### ISSUE THREAD

**Issue by bra001** [equinor/appsec#52]
Add some examples of security requirements to [Security Requirements](https://equinor.github.io/appsec/resources/security_requirements/).

This would be guidance for modern development-teams on how to create SRs for their solution.

Ex. 
Show how to derive security requirements from functional requirements.
Show how to use ASVS to help with defining security requirements.

**Comment by bra001** [comment]
> please assign this task to me and explain a bit

Hi! :) Is it more clear now?

**Comment by Shreya111111** [comment]
@bra001 plz assign this issue to me also it is in docs format right

**Comment by bra001** [comment]
@Shreya111111 assigned. The format is markdown.

**Comment by larskaare** [comment]
Dormant, closing.
