### ISSUE TITLE
Dead link to Snyk guidelines

### ISSUE THREAD

**Issue by ajaust** [equinor/appsec#66]
The link to the Snyk guidelines 
https://github.com/equinor/appsec/blob/1a2c052a351200fb675f0e7d2dc13be979bfafeb/docs/snyk/3-snyk_support.md?plain=1#L9
does not work for me. I get an 404 error when trying to access the page. It seems that `mkdocs` does not generate a page for the "Guidelines" group.

**Comment by andreabrambilla** [comment]
fixes coming in #81
