### ISSUE TITLE
security-champion: Describe the Security Champion Core Group

### ISSUE THREAD

**Issue by andreabrambilla** [equinor/appsec#97]
Addressing this issue requires some internal knowledge, so it's not really a good first issue.

Mention that the Core Group exists (with link to the internal sharepoint), and what are the group's responsibilities

Also fix the https://appsec.equinor.com/security-champion/getting-in-touch/ page, cause it talks about "representative" but what really is meant here is the Core Group

**Comment by aigelonic** [comment]
@evtil - this issue can probably be closed?
